[package]
name = "lexoffice"
version = "0.1.0"
authors = ["Enno Boland <g@s01.de>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] }
webbrowser = "0.5.2"
uuid = { version = "0.8", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0.104"

[build-dependencies]
reqwest = { version = "0.10", features = ["blocking"] }
scraper = "0.11.0"
string_morph = "0.1.0"
quote = "1.0.2"
proc-macro2 = "1.0.7"
rustfmt = "0.10.0"
