[package]
name = "lexoffice"
version = "0.1.0"
authors = ["Enno Boland <g@s01.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.1"
tokio = { version = "0.2", features = ["full"] }
reqwest = { version = "0.10.0", features = ["json", "stream"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0.104"
celes = "1.0.5"
serde_json = "1.0.44"
async-trait = "0.1.22"
tyname = "0.1.0"
derive_more = "0.99.2"
serde_plain = "0.3.0"
mime = "0.3.16"
bytes = "0.5.4"
typed-builder = "0.5.1"
derive-error = "0.0.4"
