name: CI

on: [push]

jobs:
  src-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Format Check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature_fs: ["fs", ""]
        feature_env: ["env", ""]
        target: ["wasm32-unknown-unknown", "x86_64-unknown-linux-gnu"]
        exclude:
        - target: "wasm32-unknown-unknown"
          feature_fs: "fs"
        - target: "wasm32-unknown-unknown"
          feature_env: "env"
    steps:
    - uses: actions/checkout@v2
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: >
          -p lexoffice
          --verbose
          --target ${{ matrix.target }}
          --no-default-features
          --features "${{ matrix.feature_fs }} ${{ matrix.feature_env }}"
    - name: Run tests
      uses: actions-rs/cargo@v1
      if: matrix.target == 'x86_64-unknown-linux-gnu'
      with:
        command: test
        args: >
          -p lexoffice
          --verbose
          --no-default-features
          --features "${{ matrix.feature_fs }} ${{ matrix.feature_env }}"
    - name: IRC Message Action
      uses: Gottox/irc-message-action@master
      if: failure()
      with:
        channel: "Gottox"
        nickname: gh-gottox
        message: "https://github.com/${{ github.repository }} failed on push ${{ github.event.compare }}"
