name: CI

on: [push]

jobs:
  src-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Format Check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
    - name: IRC Message Action
      uses: Gottox/irc-message-action@master
      if: failure()
      with:
        channel: "Gottox"
        nickname: gh-gottox
        message: |-
          [${{ github.workflow }} failed] ${{ github.ref }} https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
  # builds with workspaces and feature flags are currently broken for action-rs/cargo.
  # See: https://github.com/actions-rs/cargo/issues/86
  #lib-build:
  #  runs-on: ubuntu-latest
  #  defaults:
  #    run:
  #      shell: bash
  #      working-directory: ./lexoffice-cli
  #  strategy:
  #    matrix:
  #      feature_fs: ["fs", ""]
  #      feature_env: ["env", ""]
  #      target: ["wasm32-unknown-unknown", "x86_64-unknown-linux-gnu"]
  #      exclude:
  #      - target: "wasm32-unknown-unknown"
  #        feature_fs: "fs"
  #      - target: "wasm32-unknown-unknown"
  #        feature_env: "env"
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Install latest stable
  #    uses: actions-rs/toolchain@v1
  #    with:
  #      toolchain: stable
  #      target: ${{ matrix.target }}
  #      override: true
  #  - name: Build
  #    uses: actions-rs/cargo@v1
  #    with:
  #      command: build
  #      args: >
  #        --verbose
  #        --target ${{ matrix.target }}
  #        --no-default-features
  #        --features "${{ matrix.feature_fs }} ${{ matrix.feature_env }}"
  #  - name: Run tests
  #    uses: actions-rs/cargo@v1
  #    if: matrix.target == 'x86_64-unknown-linux-gnu'
  #    with:
  #      command: test
  #      args: >
  #        --verbose
  #        --no-default-features
  #        --features "${{ matrix.feature_fs }} ${{ matrix.feature_env }}"
  #  - name: IRC Message Action
  #    uses: Gottox/irc-message-action@master
  #    if: failure()
  #    with:
  #      channel: "Gottox"
  #      nickname: gh-gottox
  #      message: |-
  #        [${{ github.workflow }} failed] ${{ github.ref }} https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
  cli-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./lexoffice-cli
    steps:
    - uses: actions/checkout@v2
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: >
          --verbose
    - name: Run tests
      uses: actions-rs/cargo@v1
      if: matrix.target == 'x86_64-unknown-linux-gnu'
      with:
        command: test
        args: >
          --verbose
    - name: IRC Message Action
      uses: Gottox/irc-message-action@master
      if: failure()
      with:
        channel: "Gottox"
        nickname: gh-gottox
        message: |-
          [${{ github.workflow }} failed] ${{ github.ref }} https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
